services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - '3030:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    environment:
      - APP_ENV=production # Required
      - PUBLIC_SESSION_SECRET=${ARCANE_SESSION_SECRET}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # Optional: Set if Docker access fails
      # - DOCKER_GID=998
      # Optional: For local HTTP testing only
      # - PUBLIC_ALLOW_INSECURE_COOKIES=true
    restart: unless-stopped